### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.2

### PR DESCRIPTION
**Pull request by rvalieris**
rerender to get r3.4.1 osx builds

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @rvalieris!
Just for your information, this is now also possible: `@ conda-forge-admin, please rerender `

**Comment by rvalieris** [comment]
huh that sounds cool ! 
but I'm not sure how to use it, I can't open a empty PR can I ?

**Comment by bgruening** [comment]
Don't think so, you could add a empty line ... this is more of upgrades where you want to add a render update as well I guess.

**Comment by rvalieris** [comment]
I see, cool stuff, conda-forge is full of tricks.

**Pull request merged**
